### ISSUE TITLE
STARTTLS tugi?

### ISSUE THREAD

**Issue by randohinn** [zone-eu/mx-connect#1]
Kas mx-connect suudab `STARTTLS`-i saatmise peale mingi nipiga ellu jääda?

Hetkeseisuga, kui server vastab `220 2.0.0 Ready to start TLS`, siis järgmise commandi saatmise katse peale saavutatakse disconnect. :/

**Comment by andris9** [comment]
mx-connect ei ole seotud SMTP kihis toimuvaga. Ainus ülesanne on avada TCP socket mingi domeeni MX serveri juurde. See on sisuliselt sama mis teha `net.connect(port, host)`, lihtsalt et MX puhul on see socketi avamine mõnevõrra keerukam (A kirje asemel tuleb resolvida MX kirjed, proovida ühendusi erinevate prioriteetidega serverite vastu jne).

Kui seejärel saata sellisesse socketisse SMTP käsk STARTTLS ja server vastab "Ready to start TLS" vmt, siis seejärel tuleb algatada selle socketi peale TLS handshake. Node puhul on seda võimalik teha `tls.connect` käsuga, millele saab ette anda juba avatud socket objekti.
