### ISSUE TITLE
feat: implement faster alternative than `ipaddr.js`

### ISSUE THREAD

**Issue by titanism** [zone-eu/mx-connect#18]
Using `v8-profiler-next` and `cpupro` we identified `ipaddr.js` usage in `mx-connect` as a bottleneck in our application.

Perhaps there is a faster and more performant alternative (less CPU intensive) across a large workload than this package used by `mx-connect`.

<https://github.com/zone-eu/mx-connect/blob/7068d8de33991f1ae2f2f4c9dd83fb0a9b4cb474/lib/tools.js#L31>

**Comment by andris9** [comment]
The functionality provided by ipaddr.js is critical, and it can not be removed; I do not know a better alternative either. Maybe present your findings to the owners of the ipaddr.js project so that they can improve it. Right now, I don't think anything can be done in mx-connect about it.
