### ISSUE TITLE
bug: MTA-STS check always run (even if not explicitly set to true) *critical*

### ISSUE THREAD

**Issue by titanism** [zone-eu/mx-connect#5]
Seeing a ton of this output on CLI:

```sh
{"msg":"MTA-STS policy check succeeded","action":"mta-sts","success":true,"hostname":"x.x","host":"x.x.x.x","domain":"x.x","testing":true}
```

Seems like a breaking change or bug?

**Comment by andris9** [comment]
You're right. mx-connect logged MTA-STS information even if `mtaSts.enabled` was false. No actual checks were run. Removed those log lines in v1.4.2
