### ISSUE TITLE
feat: ability to pass `resolver` to lookup MTA-STS policy

### ISSUE THREAD

**Issue by titanism** [zone-eu/mx-connect#6]
Per <https://github.com/postalsys/mailauth/blob/29b17af91524fddbd12c3df71ad7d597fd62a996/lib/mta-sts.js#L18> there is support for custom resolver.  Perhaps `mtaSts` options can support a resolver?  Or the parent resolver can be passed along that is specified under `dnsOptions.resolve`?

**Comment by andris9** [comment]
Passed the resolver option in v1.4.2. Though it does not matter much in the context of MTA-STS as DNS is only a small part of it - most checks are run over HTTPS. DNS query is only used to detect if there is a reason to re-check the policy file, but no actual information is stored in the DNS key.
