### ISSUE TITLE
bug: `getPolicy` should be wrapped with try/catch otherwise `ESERVFAIL` errors can occur

### ISSUE THREAD

**Issue by titanism** [zone-eu/mx-connect#8]
Some DNS servers respond with `ESERVFAIL` which causes the entire chain of `mx-connect` to fail due to `_mta-sts.somedomain.com` `TXT` rrtype lookup.

This code needs to be wrapped with a try/catch and if an error occurs then it should not return a policy.

```js
    const { policy, status } = await getPolicy(delivery.decodedDomain, knownPolicy, {
        resolver: delivery.dnsOptions && delivery.dnsOptions.resolve && util.promisify(delivery.dnsOptions.resolve)
    });
```

The current workaround is to do a lookup using the same cache for `_mta-sts.somedomain.com` _before_ the call to `mx-connect`, and if it had `ESERVFAIL` then MTA-STS lookup is not performed.

Can this be fixed?

**Comment by andris9** [comment]
I think it is already fixed, are you using the latest version of mx-connect?

**Comment by andris9** [comment]
Just to make sure. You are using mx-connect v1.4.3? Because getPolicy should never throw in that version, so there is nothing to catch?

**Comment by andris9** [comment]
I'm not sure if the error check has any relevance at all anymore, as the RFC states if there are any issues, for whatever reason, when resolving the policy, it must fall back to policy=none.

**Comment by andris9** [comment]
I learned the hard way. I had a different issue - DNS was not failing, but the policy file fetching for a specific domain failed (they had a proper DNS record, but the HTTPS request timed out), so I had to check what the RFC states for situations like that and fixed it.
